export const data = [
  {
    id: "1",
    userId: "user123",
    date: "2023-01-15",
    description: "Grocery shopping at SuperMart",
    amount: -75.5,
    category: "Food",
  },
  {
    id: "2",
    userId: "user123",
    date: "2023-01-16",
    description: "Bus fare",
    amount: -3.8,
    category: "Transport",
  },
  {
    id: "3",
    userId: "user123",
    date: "2023-01-16",
    description: "Monthly Salary",
    amount: 2500.0,
    category: "Salary",
  },
  {
    id: "4",
    userId: "user123",
    date: "2023-01-17",
    description: "Online clothes purchase",
    amount: -120.0,
    category: "Shopping",
  },
  {
    id: "5",
    userId: "user123",
    date: "2023-01-18",
    description: "Electricity bill",
    amount: -85.2,
    category: "Utilities",
  },
  {
    id: "6",
    userId: "user123",
    date: "2023-01-19",
    description: "Dinner with friends",
    amount: -55.0,
    category: "Food",
  },
  {
    id: "7",
    userId: "user123",
    date: "2023-01-20",
    description: "Gas refill for car",
    amount: -40.0,
    category: "Transport",
  },
  {
    id: "8",
    userId: "user123",
    date: "2023-01-21",
    description: "Subscription service",
    amount: -15.99,
    category: "Others",
  },
  {
    id: "9",
    userId: "user123",
    date: "2023-01-22",
    description: "Gift for birthday",
    amount: -30.0,
    category: "Shopping",
  },
  {
    id: "10",
    userId: "user123",
    date: "2023-01-23",
    description: "Internet bill",
    amount: -60.0,
    category: "Utilities",
  },
];
